name: colorlighttest
description: Colorlight Test

publish_to: none

environment:
  sdk: ">=2.16.0  <3.0.0"

dependencies:
  ffi: ^1.1.2
  path: ^1.8.1
  l2ethernet: ^0.2.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
