name: l2ethernet
version: 0.3.1

homepage: https://github.com/haraldkubota/l2-ethernet
repository: https://github.com/haraldkubota/l2-ethernet
issue_tracker: https://github.com/haraldkubota/l2-ethernet/issues

description: >-
  Sending raw Ethernet frames in Dart via FFI. Usable for generating WOL packets or non-standard protocols running on Ethernet. Sending only. Linux only.

platforms:
  linux:

environment:
  sdk: ">=2.16.0  <3.0.0"

ffigen:
  output: "lib/src/eth_bindings.dart"
  headers:
    entry-points:
      - "lib/src/eth_library/sendeth.h"
  llvm-path:
    - "/usr/lib/llvm-13"

dependencies:
  ffi: ^2.1.3
  path: ^1.8.1

dev_dependencies:
  ffigen: ^14.0.1
  lints: ^5.0.0
  test: ^1.20.1
